# Parameters file for use with makeSALTSlitMaskFiles.py

# Cluster/field name/centre coords
# Output from the script will be written to MaskFiles_<name>/
name: 'GCLSTest'
RADeg: null
decDeg: null

# Mask meta data, needed for final output
proposer: 'Your Name Here'
proposalCode: 'Your Proposal Code Here'

# The format of the galaxy catalog file - either "FetchDR8", "FelipeS82", "FelipeDR8", "MattFITS", or "zCluster"
catalogFormat: "GCLS"

# Path to the galaxy catalog file - OR the database, if catalogFormat is 'zCluster'
galaxyCatalogFile: "../J0540.1-4322_selection.csv"

# Below specify arbitrary cuts on catalog for top priority targets to put slits on
targetCuts:
    - 'r > 10'
    - 'r < 30'
    - 'g-r < 99'

# Cuts below are used to specify secondary targets, these are used when no more of
# the galaxies that pass targetCuts can be placed in a mask
fillerCuts:
    - 'r > 10'
    - 'r < 30'

# Slit dimensions
slitLengthArcsec: 9.0
slitWidthArcsec: 1.5

# Minimum gap to leave between slits 
safetyArcsec: 1.0

# List of object IDs in the galaxy catalog to include in every mask (e.g., the BCG)
alwaysIncludeIDs: []

# Slit length for the above - if this was a BCG, might want a longer slit, for example
alwaysSlitLengthArcsec: 10.0

# Reference stars, for slit mask alignment - these should be selected from brightStars.reg
# To make brightStars.reg without making slit mask files, run the script with refStarIDs=[]
refStarIDs:
    - 65
    - 78
    - 109
    - 11

# Fluffy stuff
CMDCol: "g-r"

# Number of masks to make - objects will not overlap between masks unless they are in alwaysIncludeIDs
numMasks: 1
